apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-worker
  labels:
    app: {{ .Chart.Name }}-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-worker
    spec:
      enableServiceLinks: false
      imagePullSecrets: 
        - name: {{ .Chart.Name }}-registry-secret
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "ghcr.io/yomi-ai/{{ .Chart.Name }}:{{ .Values.image.tag }}"
          command: ["poetry", "run", "faust", "-A", "src.taskqueue.faust", "worker", "-l", "info"]
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-env
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 10Mi